use_frameworks!

target 'ParakhValidator_Example' do
  pod 'ParakhValidator', :path => '../'

  target 'ParakhValidator_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
